### ISSUE TITLE
Hungarian fork

### ISSUE THREAD

**Issue by progcode** [tconley/screencovid.com#26]
I just forked your project and modify to hungarian spec: [koronavirusteszt.info](koronavirusteszt.info)

https://github.com/IconoCoders/koronavirusteszt.info

Thank you!

**Comment by tconley** [comment]
Thanks. Can we add your translation? You can submit a pull request, or i will get it on it when I have time. great work

**Comment by progcode** [comment]
Sure, i will do tomorrow.

**Comment by progcode** [comment]
https://github.com/tconley/screencovid.com/pull/29
