### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sahuguet** [tconley/screencovid.com#27]
I was chatting with a former UNICEF person, looking at deploying a similar tool in Africa.
Features they are interested in:
- ability to collect information (after asking user's consent), i.e. send the data to a remote server
- support for geo-location

Do we we want to incorporate these features too, or should we let people fork?

**Comment by tconley** [comment]
i'm happy with people forking and using however works best in their projects, we just need to have a communication mechanism (or maybe an API?) in place that allows us to push the latest symptom/score data, as that is changing as more data is gathered on the virus. 

as far as data gathering goes, this is something we can talk about , but if they're talking about collecting personal identifying data, then this is probably something we want to let another org with legal protection handle.

**Comment by sahuguet** [comment]
For "latest symptom/score", we could simply have a JSON file:
- one key per question
- the value
People can then take this an enhance with their phrasing of the question and the image they want to display.

**Comment by tconley** [comment]
Also, the doctor is having conf calls this week with various global tasks force, and is specifically interested in africa as he mentioned how serious of a threat this will be there in the near future. i would love to connect your unicef africa person with the doctor. can i start an email thread with you guys?

**Comment by tconley** [comment]
> For "latest symptom/score", we could simply have a JSON file:
> 
> * one key per question
> * the value
>   People can then take this an enhance with their phrasing of the question and the image they want to display.

Agreed, we should also list the threshold(s) for what the values mean (212, etc) in that json object

This could be something that they could easily retrieve via a single http call.

**Comment by tconley** [comment]
> Also, the doctor is having conf calls this week with various global tasks force, and is specifically interested in africa as he mentioned how serious of a threat this will be there in the near future. i would love to connect your unicef africa person with the doctor. can i start an email thread with you guys?

I emailed your cornell email and connected you with the doctors - they are not on github but are actively talking about data collection and africa so now is great timing
