### ISSUE TITLE
Swipe UI Not Intuitive

### ISSUE THREAD

**Issue by mrkrause** [tconley/screencovid.com#5]
Certain demographics definitely are going to be familiar with the swipe-left-for-no, right-for-yes paradigm from Tinder (etc), but I'm worried that others, like my parents, will be totally mystified. On a computer, click+drag works, but it's even harder to discover.

I think giant YES/NO buttons might be a better way to go, with swiping (+ some kind of hint) used to navigate through the questions. The questions are all fairly short so there's plenty of room for them.

**Comment by tconley** [comment]
Agreed - this is a top issue to add the YES/NO buttons
