### ISSUE TITLE
Recommend a doctor for life-threatening conditions, regardless of score

### ISSUE THREAD

**Issue by mrkrause** [tconley/screencovid.com#6]
With the current scoring system, you can have up to TWO life threatening conditions (hypoxia+chest pain, or any of the others individually).

Even if the total score doesn't reach the COVID threshold, that's probably not ideal. I would suggest advising people to see a doctor if the score's in that range OR they've checked at least one of 
- Difficulty Breathing
- Chest pain, pressure, or irregular heart beat
- Bluish lips
- Confusion

**Comment by tconley** [comment]
Created a disclaimer with the following recommendation (per Dr Yun)... 

I agree about advising folks to see a doctor for the conditions you mentioned, there should be a message after they've gone through symptoms in the empty space after the cards are swiped.

* If you’re experiencing a life- or limb-threatening emergency, call 911 or the number for your local emergency service. This tool is not a substitute for professional medical advice, diagnosis, or treatment. Always consult a medical professional for serious symptoms or emergencies.
